# GoReleaser v2 配置
version: 2

project_name: chatlog-tcotc



before:
  hooks:
    - go mod tidy
    - go run github.com/akavel/rsrc@latest -arch amd64 -ico internal/tray/icon.ico -o internal/tray/rsrc_windows_amd64.syso
    - go run github.com/akavel/rsrc@latest -arch arm64 -ico internal/tray/icon.ico -o internal/tray/rsrc_windows_arm64.syso

builds:
  - id: chatlog-builds
    binary: chatlog
    ldflags:
      - -s -w -X {{ .Env.GITHUB_REPOSITORY }}/pkg/version.Version={{.Version}}-{{.ShortCommit}}
    env:
      - CGO_ENABLED=1
    tags:
      - fts5
      - nowhispercpp
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: darwin
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=o64-clang
          - CXX=o64-clang++
      - goos: darwin
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=oa64-clang
          - CXX=oa64-clang++
      - goos: windows
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++
      - goos: windows
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=/llvm-mingw/bin/aarch64-w64-mingw32-gcc
          - CXX=/llvm-mingw/bin/aarch64-w64-mingw32-g++
      - goos: linux
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=x86_64-linux-gnu-gcc
          - CXX=x86_64-linux-gnu-g++
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++

upx:
  - enabled: true
    goos: [darwin, windows, linux]
    goarch: [amd64, arm64]
    compress: best
    lzma: true

archives:
  - id: default
    formats: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# 配置 GitHub Release
release:
  draft: true
  prerelease: auto
  mode: replace

# Docker 镜像配置
# FIXME: 等待 goreleaser 2.12 更新后使用 dockers_v2
dockers:
  # GitHub Container Registry - amd64
  - ids:
      - chatlog-builds
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName | tolower }}:{{ .Tag }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName | tolower }}:{{ .Tag }}-{{ .ShortCommit }}-amd64"
    dockerfile: Dockerfile
    extra_files:
      - script/docker-entrypoint.sh
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName | tolower }}"
      - "--label=org.opencontainers.image.description=chat log tool, easily use your own chat data."
      - "--label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
      - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

  # GitHub Container Registry - arm64
  - ids:
      - chatlog-builds
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName | tolower }}:{{ .Tag }}-arm64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName | tolower }}:{{ .Tag }}-{{ .ShortCommit }}-arm64"
    dockerfile: Dockerfile
    extra_files:
      - script/docker-entrypoint.sh
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName | tolower }}"
      - "--label=org.opencontainers.image.description=chat log tool, easily use your own chat data."
      - "--label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
      - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

  # Docker Hub - amd64 (仅在设置了 DOCKERHUB_USERNAME 时构建)
  - ids:
      - chatlog-builds
    image_templates:
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .ProjectName | tolower }}:{{ .Tag }}-amd64"
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .ProjectName | tolower }}:{{ .Tag }}-{{ .ShortCommit }}-amd64"
    dockerfile: Dockerfile
    extra_files:
      - script/docker-entrypoint.sh
    use: buildx
    goos: linux
    goarch: amd64
    skip_push: auto
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName | tolower }}"
      - "--label=org.opencontainers.image.description=chat log tool, easily use your own chat data."
      - "--label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
      - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

  # Docker Hub - arm64 (仅在设置了 DOCKERHUB_USERNAME 时构建)
  - ids:
      - chatlog-builds
    image_templates:
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .ProjectName | tolower }}:{{ .Tag }}-arm64"
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .ProjectName | tolower }}:{{ .Tag }}-{{ .ShortCommit }}-arm64"
    dockerfile: Dockerfile
    extra_files:
      - script/docker-entrypoint.sh
    use: buildx
    goos: linux
    goarch: arm64
    skip_push: auto
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName | tolower }}"
      - "--label=org.opencontainers.image.description=chat log tool, easily use your own chat data."
      - "--label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
      - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

# Docker manifest 配置用于多架构镜像
docker_manifests:
  # GitHub Container Registry manifests
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName | tolower }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName | tolower }}:{{ .Tag }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName | tolower }}:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName | tolower }}:{{ .ShortCommit }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName | tolower }}:{{ .Tag }}-{{ .ShortCommit }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName | tolower }}:{{ .Tag }}-{{ .ShortCommit }}-arm64"

  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName | tolower }}:latest"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName | tolower }}:{{ .Tag }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName | tolower }}:{{ .Tag }}-arm64"
    skip_push: auto

  # Docker Hub manifests (仅在设置了 DOCKERHUB_USERNAME 时推送)
  - name_template: "{{ .Env.DOCKERHUB_USERNAME }}/{{ .ProjectName | tolower }}:{{ .Tag }}"
    image_templates:
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .ProjectName | tolower }}:{{ .Tag }}-amd64"
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .ProjectName | tolower }}:{{ .Tag }}-arm64"
    skip_push: auto

  - name_template: "{{ .Env.DOCKERHUB_USERNAME }}/{{ .ProjectName | tolower }}:{{ .ShortCommit }}"
    image_templates:
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .ProjectName | tolower }}:{{ .Tag }}-{{ .ShortCommit }}-amd64"
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .ProjectName | tolower }}:{{ .Tag }}-{{ .ShortCommit }}-arm64"
    skip_push: auto

  - name_template: "{{ .Env.DOCKERHUB_USERNAME }}/{{ .ProjectName | tolower }}:latest"
    image_templates:
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .ProjectName | tolower }}:{{ .Tag }}-amd64"
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .ProjectName | tolower }}:{{ .Tag }}-arm64"
    skip_push: auto
